- name: Start OpenLDAP container
  docker_container:
    name: ldap
    image: "{{ _openldap.image }}:{{ _openldap.version | default('latest')  }}"
    pull: true
    state: started
    restart: yes
    restart_policy: always
    restart_retries: 5
    published_ports:
      - "389:389"
    env:
      SLAPD_PASSWORD: secret
      SLAPD_DOMAIN: example.de
      SLAPD_ORGANIZATION: Example
    networks:
      - name: application

- name: Give LDAP server a bit of time to get ready
  pause: seconds=3

- name: Load devteam users and groups from ldif
  command: docker exec ldap bash -l -c /load-devteam-ldif.sh > /dev/null 2>&1
  ignore_errors: yes
