docker_default:
  gpg_server: "hkp://p80.pool.sks-keyservers.net:80"
  gpg_key: "58118E89F3A912897C070ADBF76221572C52609D"
  apt_repository: "deb https://apt.dockerproject.org/repo {{ ansible_lsb.id|lower }}-{{ ansible_lsb.codename|lower }} main"
  docker_opts: "{{ _docker.insecure_registry }}"
